name: CD
on:
  push:
    branches: [ "master" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build app
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: decahthuk/tripapi:1.2.1

  update-yc:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1.0.1
        env:
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          JWT_SECRET_ACCESS: ${{ secrets.JWT_SECRET }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          vm-name: excalibur
          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
          user-data-path: './yc/user-data.yaml'
          docker-compose-path: './yc/docker-compose.yaml'